[ui.colors]
"selected" = { bg = "#151515" }
"confirmation selected" = { bg = "#151515" }
"revisions details selected" = { bg = "#151515" }
"revset completion selected" = { bg = "#151515" }
"menu selected" = { bg = "#151515" }
